set(_CATKIN_CURRENT_PACKAGE "begommer_tutorials")
set(begommer_tutorials_VERSION "0.0.0")
set(begommer_tutorials_MAINTAINER "illyms <illyms@todo.todo>")
set(begommer_tutorials_PACKAGE_FORMAT "2")
set(begommer_tutorials_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(begommer_tutorials_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(begommer_tutorials_BUILDTOOL_DEPENDS "catkin")
set(begommer_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(begommer_tutorials_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(begommer_tutorials_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(begommer_tutorials_TEST_DEPENDS )
set(begommer_tutorials_DOC_DEPENDS )
set(begommer_tutorials_URL_WEBSITE "")
set(begommer_tutorials_URL_BUGTRACKER "")
set(begommer_tutorials_URL_REPOSITORY "")
set(begommer_tutorials_DEPRECATED "")